### ISSUE TITLE
Make the "more of my games" link clickable

### ISSUE THREAD

**Issue by gonutz** [eboatwright/eboatwright.github.io#1]
Your `Games` page says "You can find more here!" and the word "here" is a clickable link. However it looks the same as the rest of the words. I suggest you either highlight the "here" or better yet make the whole thing clickable and maybe underline it or highlight it in a different way so that you immediately see that it is a link.

**Comment by eboatwright** [comment]
Oops! Sorry I missed this post. Github didn't notify me for some reason. I'll fix that next chance I get!

**Comment by gonutz** [comment]
Nice, thanks for getting back at me :-)

**Comment by eboatwright** [comment]
Fixed it! :D
